name: Build Openresty

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: patch nginx-openresty
        run: | 
         make -j "$(nproc)"
         mv openresty-*.tar.gz openresty.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.event_name != 'pull_request'
        with:
          prerelease: false
          repo_token: ${{ github.token }}
          title: latest
          automatic_release_tag: latest
          files: |
            openresty.tar.gz
